### ISSUE TITLE
Implement Workload API Default client 

### ISSUE THREAD

**Issue by Andres-GC** [HewlettPackard/py-spiffe#13]
This issue is to implement a primitive wrapper around the Workload API

For the most part, the implementation should more or less be a wrapper around the Workload API gRPC client, converting to/from protobufs. All of the methods on the client are synchronous and straightforward.

Depends on [#6](https://github.com/HewlettPackard/py-spiffe/issues/6)

**Comment by scotte** [comment]
Depends on #6

**Comment by scotte** [comment]
https://github.com/HewlettPackard/py-spiffe/pull/31
