### ISSUE TITLE
Why does py-spiffe isn't in the SPIRE 

### ISSUE THREAD

**Issue by raissonsouto** [HewlettPackard/py-spiffe#133]
Reviewing the SPIRE documentation, I noticed that `py-spiffe` it is not available at the following link: https://spiffe.io/docs/latest/deploying/libraries/.

Is this due to a related issue or simply because no one has submitted it yet? If it's a matter of no submissions, may I contribute?

**Comment by maxlambrecht** [comment]
Thank you for your suggestion! I agree that it's a great idea. However, I'd like to ask for a bit of patience before you proceed with submitting it to the SPIFFE repository. I'm in the midst of preparing to publish the library's first version on PyPI. This will greatly facilitate the integration and usage of the library.

**Comment by maxlambrecht** [comment]
Hey @raissonsouto, I appreciate your patience! 

`py-spiffe` library is now officially available on PyPI, divided into two modules:

- **SPIFFE Core**: [spiffe](https://pypi.org/project/spiffe/) - The foundational module for working with SPIFFE IDs and SVIDs, and provides the WorkloadAPI client, X509Source, and JwtSource.
- **SPIFFE TLS**: [spiffe-tls](https://pypi.org/project/spiffe-tls/) - Extends the core functionality to facilitate secure TLS communication with some convenient wrappers around [pyOpenSSL](https://pypi.org/project/pyOpenSSL/).

Would you be able to update the spiffe.io documentation to include references to these module? It would greatly benefit users looking to integrate SPIFFE in Python projects. 

Thanks!

**Comment by raissonsouto** [comment]
Done :)
