### ISSUE TITLE
Translate gRPC responses for JWT SVIDs into Python objects

### ISSUE THREAD

**Issue by Andres-GC** [HewlettPackard/py-spiffe#20]
Implement required methods to translate gRPC messages to Python Objects.
For example, from a [JWTSVIDResponse](https://github.com/HewlettPackard/py-spiffe/blob/master/proto/workload.proto#L60) message to a [JwtSvid](https://github.com/HewlettPackard/py-spiffe/blob/master/src/pyspiffe/svid/jwt_svid.py#L5) object.
Same for  `JWTBundlesResponse`, `ValidateJWTSVIDResponse`

**Comment by maxlambrecht** [comment]
This is trivial having already implemented the python SVID types, this will be done as part of #61
