### ISSUE TITLE
Translate gRPC responses for X509 SVIDs into Python Objects

### ISSUE THREAD

**Issue by Andres-GC** [HewlettPackard/py-spiffe#21]
Implement required methods to translate gRPC messages to Python Objects.
From a [X509SVIDResponse](https://github.com/HewlettPackard/py-spiffe/blob/master/proto/workload.proto#L12) message to a [X509Svid](https://github.com/HewlettPackard/py-spiffe/blob/master/src/pyspiffe/svid/x509_svid.py#L6) object.

**Comment by maxlambrecht** [comment]
This is trivial having already implemented the python SVID types, this will be done as part of #61
