### ISSUE TITLE
The tox venv doesn't have dependencies from the Pipfile

### ISSUE THREAD

**Issue by scotte** [HewlettPackard/py-spiffe#44]
I found an issue where the tox venv doesn't have all the dependencies specified in the Pipfile. Tox doesn't support Pipfile, but it does support requirements.txt and I found a way to have that generated as part of `make dev` to refresh dependencies. I don't know if there's a better way, but I'll toss out my Pull Request as one approach.

**Comment by maxlambrecht** [comment]
Can be marked as resolved ?

**Comment by scotte** [comment]
This issue was deferred (and the pull request closed) pending further research, because this was solving an issue that is not currently a concern, and because there are competing approaches regarding the best behavior.

The original issues I was trying to solve here:

1. Dependencies are specified in more than one file, requiring maintaining them in two places.
2. Versions of dependencies used for development and tests are not necessarily the version specified in the package.

The original pull request is less than ideal as the generated dependencies for packaging were not just the shallow list specified in Pipfile, but also included some transitive dependencies. Instead, best practice is to specify only top-level dependencies. Additionally, there are conflicts between various best practices, such as the Python package best practice which does not recommend pinning versions.

Until this has potential to be a real problem, the best option is chosen, and an implementation created to handle deficiencies noted above, this issue is deferred for now.

**Comment by maxlambrecht** [comment]
No longer relevant as the project is being migrated to using Poetry as dependency management.
